### ISSUE TITLE
OhdsiStudies scraper doesn't pick up study without img tag for badge

### ISSUE THREAD

**Issue by keesvanbochove** [OHDSI/ShinyDeploy#120]
I noticed that the PioneerWatchfulWaiting study isn't picked up in data.ohdsi.org/OhdsiStudies, probably because we aren't using the img tag since this commit: https://github.com/ohdsi-studies/PioneerWatchfulWaiting/commit/9376b90e2f9cdea90e2192903bcb43cfb9c7abf0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

See https://github.com/OHDSI/ShinyDeploy/blob/1ab13a351c706f01f32340b0517584858b0fbaed/OhdsiStudies/githubScraper.R#L69

Should we revert to using the img tag or would you like to update the code to for instance only match the URL of the badge?

**Comment by schuemie** [comment]
Should now be fixed. 

Is the study status really still 'Started'?
