### ISSUE TITLE
Missing dependency 'survminer' on ShinyDeploy server

### ISSUE THREAD

**Issue by keesvanbochove** [OHDSI/ShinyDeploy#122]
@schuemie @leeevans this Shiny App has a dependency on package 'survminer', which currently isn't installed on the OhdsiShiny server (see https://data.ohdsi.org/PioneerWatchfulWaiting/ > Time to Event tab). What would be the right way to declare this?

_Originally posted by @keesvanbochove in https://github.com/OHDSI/ShinyDeploy/issues/121#issuecomment-882601699_

**Comment by leeevans** [comment]
@keesvanbochove I will install the latest version of the 'survminer' R package on the OHdsiShiny server.

**Comment by keesvanbochove** [comment]
Thanks @leeevans! We are one step closer now, but there also seems to be a dependency on a newer version of `Rcpp`. When opening the 'Time to Event' tab on https://data.ohdsi.org/PioneerWatchfulWaiting, it shows an error message to that effect (I can't copy it because the website doesn't seem to load right now).

**Comment by leeevans** [comment]
@keesvanbochove - the shiny server has now been upgraded to use rocker/shiny:4.1.0 and the Time to Event tab is working so I am closing this issue.
