### ISSUE TITLE
Query Library isn't working, shiny app error

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/ShinyDeploy#136]
Per @leeevans on the [forum](https://forums.ohdsi.org/t/query-library-website-error-messages/15103/3):

and include the below error message from the Shiny server log:

[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'querylibrary-rendered.knit' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
File www/rendered.css not found in resource path

Warning: Error in : pandoc document conversion failed with error 99
  119: stop
  118: stop2
  117: pandoc_convert
  116: convert
  115: rmarkdown::render
  114: createRenderedHtml
  113: <reactive> [/srv/shiny-server/QueryLibrary/server.R#56]
   97: renderedFilename
   96: renderText [/srv/shiny-server/QueryLibrary/server.R#64]
   95: func
   82: renderFunc
   81: output$html
    1: runApp

**Comment by leeevans** [comment]
@MelaniePhilofsky  @bmosseveld has fixed the issue and the QueryLibrary Shiny application is working now. Thanks for all your help Mees!
