### ISSUE TITLE
Application exits unexpectedly

### ISSUE THREAD

**Issue by bdemeulder** [OHDSI/ShinyDeploy#148]
The Pioneer Watchful Waiting shiny app crashes when loading the Cohort Characterization tab, which I cannot reproduce locally. We have not made any changes to it in the past week. I also cannot access the Java Script error console to check the error further. 

Any help?

![image](https://user-images.githubusercontent.com/11734167/146203007-3514088a-ad14-46ce-bb08-c77a883c11dc.png)

**Comment by bdemeulder** [comment]
@keesvanbochove, has there been changes to the shiny server recently? Do you have access to the Javascript error console?

**Comment by keesvanbochove** [comment]
I don't know, that is a question you can better ask @leeevans who is managing this infrastructure.

**Comment by leeevans** [comment]
@bdemeulder I believe the javascript error console being referenced is the console tab in the chrome browser when you enable developer tools. I see the below error information:


Attaching package: ‘shinydashboard’

The following object is masked from ‘package:graphics’:

    box


Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

**Killed
shiny-server-client.min.js:1 The application unexpectedly exited.**

Diagnostic information has been dumped to the JavaScript error console.

**Comment by leeevans** [comment]
@bdemeulder 

That appears to be a very generic error message but I see some info at the below url on how to get additional info for troubleshooting. Enabling preserve logs requires restarting the shiny server. I will do that later today and hopefully we can track down the cause of the issue.

https://stackoverflow.com/questions/42265329/shiny-server-connection-closed-info-typeclose-code4503-reasonthe

**Comment by leeevans** [comment]
@bdemeulder It seems the shiny app is being killed because it is using all available memory on the server.  This may be because it is loading a lot of data into memory. If additional data was recently uploaded, it may have been enough to exceed the memory limit. 

I've increased the swap file size to accommodate it.

**Comment by bdemeulder** [comment]
@leeevans Thanks, it works again. 
Locally, it does needs close to 11 Gb of RAM when pulling the cohort characterization tab, so it is a large file indeed.

We do expect another big dataset in the coming days/week, more than doubling the number of patients. Is the system going to be able to handle that? How can we prepare for it?

**Comment by schuemie** [comment]
Keeping 11GB in memory is not ok. Either use the file system or a database to hold the data, and only load what you're displaying, when you're displaying it.
