### ISSUE TITLE
No survminer package available in shiny app

### ISSUE THREAD

**Issue by bdemeulder** [OHDSI/ShinyDeploy#154]
The time to event in the PIONEER Watchfull waiting shiny app does not work anymore. It throws the following error:  
Error: there is no package called 'survminer' (see screengrab)

![image](https://user-images.githubusercontent.com/11734167/155736156-3b50b38c-4675-4a91-9882-513736b63b7c.png)

@leeevans, could you check if the package is indeed installed?

**Comment by leeevans** [comment]
added missing OS library dependency libnlopt-dev for survminer package
